# Generated by Django 2.2.6 on 2019-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uploaded_file', models.FileField(upload_to='files/csv')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
